INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (1, 'Математика', 1);
INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (2, 'Информатика', 1);
INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (3, 'Архитектура', 2);
INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (4, 'Градостроительство', 2);
INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (5, 'Строительство', 2);
INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (6, 'Поварское дело', 3);
INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (7, 'Швейное дело', 4);
INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (8, 'Дело производство', 5);
INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (9, 'Русский язык', 6);
INSERT INTO journal.napr_podg (id_napr, name, id_kaf) VALUES (10, 'КУльтура речи', 6);